### ISSUE TITLE
OUT OF MEMORY with MsEvaluator

### ISSUE THREAD

**Issue by nymph332088** [dapengchen123/crf_affinity#1]
Hi, Thanks for releasing the code.
To whomever is using this software, may you share the hardware environment you have when you run the standard_batch.sh? 
The code I run is 
`CUDA_VISIBLE_DEVICES=0,1,2,3 python3 crfjointlossfpn.py -b 66 --epoch 43  --instances_num 6 --cnnlr 1e-2 --logs-dir logs/evaluate_feature-66-6`

I have 4 Titan Xp GPUs, each of which has 12GB. I am using pytorch 0.4.
However, I always have **out of memory** error when evaluating. 
It throws the error when extracting features using the ResNetFPN backbone as shown in the following messages.
The weird thing is CUDA_VISIBLE_DEVICES=0,1 or 0,1,2,3 both gave me the same error at the same place.

BTW, in the `crfjointlossfpn.py` file, from line 124-150, if I do not understand wrongly, the best model is selected based on test performance not the validation performance, which is a little bit disobeying what people normally do.

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "crfjointlossfpn.py", line 217, in <module>
    main(parser.parse_args())
  File "crfjointlossfpn.py", line 125, in main
    top1 = evaluator.evaluate(query_loader, gallery_loader, dataset.query, dataset.gallery)
  File "/home/test/Development/PersonReID/crf_affinity/reid/evaluator/msevaluator.py", line 140, in evaluate
    distmat = self.compute_distmat(queryloader, galleryloader)
  File "/home/test/Development/PersonReID/crf_affinity/reid/evaluator/msevaluator.py", line 192, in compute_distmat
    queryfeat1, queryfeat2, queryfeat3 = self.extractfeature(queryloader)
  File "/home/test/Development/PersonReID/crf_affinity/reid/evaluator/msevaluator.py", line 114, in extractfeature
    query_feat1, query_feat2, query_feat3 = self.cnnmodel(imgs)
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/Development/PersonReID/crf_affinity/reid/models/resfpnnet.py", line 117, in forward
    x = module(x)
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/miniconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/resnet.py", line 84, in forward
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/miniconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.cu:58

**Comment by dapengchen123** [comment]
The code is tested over pytorch3.0. As far as I know, pytorch has some modification for the testing data. The 82 line in   https://github.com/dapengchen123/crf_affinity/blob/master/reid/evaluator/msevaluator.py
`  
      imgs = Variable(imgs, volatile=True)
`
should be modified in pytorch4.0.

**Comment by ningxia** [comment]
@dapengchen123  
Could you please kindly answer the question mentioned in @nymph332088 's original post? 

"BTW, in the crfjointlossfpn.py file, from line 124-150, if I do not understand wrongly, the best model is selected based on test performance not the validation performance, which is a little bit disobeying what people normally do."  

Thank you very much!

**Comment by dapengchen123** [comment]
@nymph332088 @ningxia   https://pytorch.org/2018/04/22/0_4_0-migration-guide.html.   " The volatile flag is now deprecated and has no effect. Previously, any computation that involves a Variable with volatile=True wouldn’t be tracked by autograd. This has now been replaced by a set of more flexible context managers including torch.no_grad(), torch.set_grad_enabled(grad_mode), and others."

So for pytorch4.0,  "imgs = Variable(imgs, volatile=True)" is invalided. I will modified the code

**Comment by dapengchen123** [comment]
@ningxia    There is no clear description for the dataset about how many images should be used for validation.  You can select the best parameters by separating the training set, and train the final model over all the  training set.

**Comment by ningxia** [comment]
@dapengchen123 
Thank you for your prompt answers!
I didn't mean the train/validation split. If I understand your code and the original Open-Reid code correctly, it seemed that in your code, it evaluated the Top-1 CMC using the TEST (line 125 dataset.query and dataset.gallery) and saved the best weights base on this Test set Top-1 CMC, rather the original Open-Reid code used VALIDATION (examples/triplet_loss.py line 147: dataset.val dataset.val) to evaluate Top-1 CMC and save weights, while training. I think both @nymph332088 and I share the same confusion. I would be much appreciated if you could help us out on this.

**Comment by dapengchen123** [comment]
@ningxia @nymph332088   Yes, that is not appropriate. I will change that. Thanks!  In fact, I didn't use the saved the best model in the training, but report the results when the training is convergence.  Actually, I follow the code from Open-Reid, but I didn't notice the problem. :)

**Comment by ningxia** [comment]
@dapengchen123 
Thank you very much for your explanation.

**Comment by dapengchen123** [comment]
@ningxia  A new branch for pytorch 4.0 is added.

**Comment by ningxia** [comment]
@dapengchen123 Thank you very much for letting me know!
